spring:
  datasource:
    password: ${DB_PASSWORD:mysql}
    username: ${DB_USERNAME:root}
    url: jdbc:mysql://localhost:3306/workshop_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver